services:
  event-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-management
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      ENVIRONMENT: 'local'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      MAX_EVENT_SEAT_HOLD_TIME_IN_S: '45'
    volumes:
      - ./src:/app/src
      - ./openapi.yaml:/app/openapi.yaml
    # If time permitted, I would setup debug profiles to allow for easier debugging
    command: npm run start:debug

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  pgdata:
    driver: local
  cache:
    driver: local
